version: "3"
services:
    store-db:
        image: postgres:14-alpine
        container_name: store-db
        ports:
            - "5432:5432"
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=store
