version: "3"
services:
    store-db:
        image: postgres:14-alpine
        container_name: store-db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=store
    shop-db:
        image: postgres:14-alpine
        container_name: shop-db
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=shop
    zookeeper-server:
        image: bitnami/zookeeper:3.7
        container_name: zookeeper-server
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka-server:
        image: bitnami/kafka:3
        container_name: kafka-server
        depends_on:
            - zookeeper-server
        ports:
            - "9093:9093"
        environment:
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
            - KAFKA_CFG_LISTENERS=CLIENT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-server:9092
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    shop-app:
        container_name: shop-app
        build:
            context: /shop
            dockerfile: /Dockerfile
        depends_on:
            - shop-db
            - kafka-server
        restart: always
        ports:
            - "8081:8081"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://shop-db:5432/shop
            - SPRING_FLYWAY_URL=jdbc:postgresql://shop-db:5432/shop
            - SPRING_KAFKA_BOOTSTRAP-SERVERS=http://kafka-server:9092
    store-app:
        container_name: store-app
        build:
            context: /store
            dockerfile: /Dockerfile
        depends_on:
            - store-db
            - kafka-server
        restart: always
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://store-db:5432/store
            - SPRING_FLYWAY_URL=jdbc:postgresql://store-db:5432/store
            - SPRING_KAFKA_BOOTSTRAP-SERVERS=http://kafka-server:9092