spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/store
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost:5433/store
    user: postgres
    password: postgres
    sql-migration-separator: _