spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost:5432/store
    user: postgres
    password: postgres
    sql-migration-separator: _

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: orders
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
